spring.application.name=JpaDemo

spring.datasource.url=jdbc:postgresql://localhost:5433/appdb?user=postgres&password=postgres123&options=-c%20TimeZone=Asia/Kolkata
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Kolkata

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql